### ISSUE TITLE
Displayword  look-up: Instructions unclear, looked up your skirt

### ISSUE THREAD

**Issue by Myfistus** [hayleethegamer/HayleebotBugandFreedback#4]
The instructions for usage are a bit unclear and confusing 

> How to use this command: !displaywordlookup [limit] [word/phrase] [word or phrase to look up] or !displaywordlooup [word/phrase] [word or phrase to look up.]
> 
> limit is the number of messages to look back.
> word/phrase is either word or phrase, depending on if you want to look up a word or a phrase.
> word or phrase to look up is exactly That, the word or phrase you want to look up.
> Example: !displaywordlookup 2000 word hello or !displaywordlookup 2000 phrase hello there

it should be something like 

 !displaywordlookup [#of posts to search] [Whether WORD or PHRASE] [word or phrase to look up]
Examples: !displaywordlookup 2000 word hello ; !displaywordlookup 2000 phrase hello there

**Comment by hayleethegamer** [comment]
Command Useage changed to: 
> How to use this command: !displaywordlookup [# of posts to search] [If it's a word/phrase] [word or phrase to look up]
You are not requried to give the # of posts to search, if not given it will look at the past 1000
Example: !displaywordlookup 2000 word hello or !displaywordlookup 2000 phrase hello there

**Comment by Myfistus** [comment]
Blah blah blah comment
